Acknowledgement updated for reset
ClobWise/crm-front pull request #14
Opened 2024-02-19 16:18 UTC by Shevil27

I have added a few more react components inside the acknowledgement file.
-If the reset password link's token is valid, then it will move forward, else it ill show a 404 error.
-instead of static href's, used dynamic href.

2024-02-19 17:24 UTC, ubcharu commented on src/public/view/Reset/Forgot.tsx
> +import { EmailSent } from './acknowledgement';
Components containing React components is always `UpperCamelCase`.

2024-02-19 17:24 UTC, ubcharu commented on src/public/view/Reset/Forgot.tsx
> +import { useHref } from '../../../util/location';
Import order. Parent component first and then all the way down to the current working directory.

2024-02-19 17:25 UTC, ubcharu commented on src/public/view/Reset/Reset.tsx
> +  console.log(response);
Remove `console.log`.

2024-02-19 17:27 UTC, ubcharu commented on src/public/view/Reset/Reset.tsx
> +        {info.isPending ? (
This is wrong. You should show form when info is successful and when submit is successful i.e. `reset.isSuccessful`, then show `ResetPasswordSuccessful` component.

Looks like, the conditions are not tested.

2024-02-19 17:27 UTC, ubcharu commented on src/public/view/Reset/acknowledgement.tsx
> +export function ResetPasswordSuccessfull() {
Name should be `ResetPasswordSuccessful` and not `ResetPasswordSuccessfull`.

2024-02-19 17:28 UTC, ubcharu commented on src/public/view/Reset/acknowledgement.tsx
> +      <Heading level={4}>Reset password link not found</Heading>
You cannot have heading inside a heading. That will result in bad HTML markup.

2024-02-19 17:29 UTC, ubcharu requested changes
@Shevil27, Please make necessary changes.

2024-02-21 11:03 UTC, ubcharu commented on src/public/view/Reset/Reset.tsx
> +  const tokenState: State = info.isSuccess ? 'ValidToken' : 'InvalidToken';
The whole idea of creating `State` type is such that your application remains in exactly one state. If you have two state variables, then it defeats the purpose of create single state value.

2024-02-21 11:03 UTC, ubcharu commented on src/public/view/Reset/Reset.tsx
> +        {tokenState === 'ValidToken' && resetState === 'ResetFailure' && (
This multiple conditions should not happen. Only single state check should be there.

2024-02-21 11:04 UTC, ubcharu commented on src/public/view/Reset/Reset.tsx
> +        {resetState === 'ResetSuccess' && <ResetPasswordSuccessfull />}
Component name should be `ResetPasswordSuccessful`!

2024-02-21 11:04 UTC, ubcharu requested changes
Some more review comments!

2024-02-25 10:58 UTC, mistyharsh approved these changes

2024-02-25 10:59 UTC, merged